version: '3.9'
services:
  petshop-gjnv-frontend:
    container_name: petshop-gjnv-frontend
    image: ${DOCKER_USERNAME}/petshop-gjnv-frontend
    ports:
      - "3000:3000"
    restart: on-failure
    networks:
      - app-private-network

  petshop-gjnv-database:
    container_name: petshop-gjnv-database
    image: ${DOCKER_USERNAME}/petshop-gjnv-database
    environment:
      POSTGRES_PASSWORD: ${DB_USER}
      POSTGRES_DB: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    restart: on-failure
    networks:
      - app-private-network

networks:
  app-private-network:
    driver: bridge
    name: app-private-network